---
- name: Gather os specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
  tags: vars

- name: Ensure requried packages are installed for Debian
  ansible.builtin.package:
    name: "{{ ansible_userspace_packages }}"
    state: present
  become: true
  become_user: root

- name: Enable redis-server
  ansible.builtin.service:
    name: redis-server
    state: started
    enabled: true
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: root

- name: Ensure the ansible userspace user exists
  ansible.builtin.user:
    name: "{{ ansible_userspace_user }}"
    createhome: true
    state: present
  become: true
  become_user: root

- name: Get home directory of ansible userspace user
  ansible.builtin.getent:
    database: passwd
    key: "{{ ansible_userspace_user }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Set home directory var for ansible userspace user
  ansible.builtin.set_fact:
    ansible_userspace_user_home: "{{ getent_passwd[ansible_userspace_user][4] }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Lookup user group
  ansible.builtin.set_fact:
    ansible_userspace_user_group: "{{ lookup('pipe', 'id -gn') }}"
  become: true
  become_user: "{{ ansible_userspace_user }}"

- name: Install required dependencies into the virtual python environment
  ansible.builtin.pip:
    name:
      - python-debian
      - redis
      - ansible
      - ansible-lint
      - ansible-navigator
      - argcomplete
    virtualenv: "{{ ansible_userspace_user_home }}/{{ ansible_userspace_venv_subdir }}"
  notify: Enable python autocomplete
  become: true
  become_user: "{{ ansible_userspace_user }}"

- name: Ensure ~/.local/bin/ exists
  ansible.builtin.file:
    path: "{{ ansible_userspace_user_home }}/.local/bin/"
    state: directory
    owner: "{{ ansible_userspace_user }}"
    group: "{{ ansible_userspace_user_group }}"
    mode: "0770"
  become: true
  become_user: "{{ ansible_userspace_user }}"

- name: Link some useful bind from venv to ~/.local/bin/
  ansible.builtin.file:
    src: "{{ ansible_userspace_user_home }}/{{ ansible_userspace_venv_subdir }}/bin/{{ item }}"
    dest: "{{ ansible_userspace_user_home }}/.local/bin/{{ item }}"
    state: link
    owner: "{{ ansible_userspace_user }}"
    group: "{{ ansible_userspace_user_group }}"
    follow: false
  loop:
    - ansible
    - ansible-lint
    - ansible-playbook
    - ansible-galaxy
    - ansible-navigator
    - python3
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: "{{ ansible_userspace_user }}"
