---
- name: Install requirements
  ansible.builtin.package:
    name:
      - redis-server
      - python3-full
    state: present

- name: Enable redis-server
  ansible.builtin.service:
    name: redis-server
    state: started
    enabled: true

- name: Install redis and ansible python library via pip
  ansible.builtin.pip:
    name:
      - redis
      - ansible
    virtualenv: "/home/{{ ansible_install_for_user }}/.local"
  become: true
  become_user: "{{ ansible_install_for_user }}"
